version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: patient-postgres
    environment:
      POSTGRES_DB: hospital_patient_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - patient_pg_data:/var/lib/postgresql/data

  patient-service:
    image: patient-service:1.0
    container_name: patient-service
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hospital_patient_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always

volumes:
  patient_pg_data:
